"""Created all other tables

Revision ID: 61cdd79b940e
Revises: b816391cc96f
Create Date: 2024-12-19 16:14:45.926478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61cdd79b940e'
down_revision: Union[str, None] = 'b816391cc96f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brands_id'), 'brands', ['id'], unique=False)
    op.create_index(op.f('ix_brands_name'), 'brands', ['name'], unique=False)
    op.create_table('drivetrains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drivetrains_id'), 'drivetrains', ['id'], unique=False)
    op.create_index(op.f('ix_drivetrains_name'), 'drivetrains', ['name'], unique=False)
    op.create_table('emission_standards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emission_standards_id'), 'emission_standards', ['id'], unique=False)
    op.create_index(op.f('ix_emission_standards_name'), 'emission_standards', ['name'], unique=False)
    op.create_table('equipment_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_categories_id'), 'equipment_categories', ['id'], unique=False)
    op.create_index(op.f('ix_equipment_categories_name'), 'equipment_categories', ['name'], unique=False)
    op.create_table('fuels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fuels_id'), 'fuels', ['id'], unique=False)
    op.create_index(op.f('ix_fuels_name'), 'fuels', ['name'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_city'), 'locations', ['city'], unique=False)
    op.create_index(op.f('ix_locations_country'), 'locations', ['country'], unique=False)
    op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=False)
    op.create_table('transmissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('number_of_gears', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transmissions_id'), 'transmissions', ['id'], unique=False)
    op.create_index(op.f('ix_transmissions_name'), 'transmissions', ['name'], unique=False)
    op.create_table('vehicle_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_types_id'), 'vehicle_types', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_types_name'), 'vehicle_types', ['name'], unique=False)
    op.create_table('body_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('vehicle_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_type_id'], ['vehicle_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_body_types_id'), 'body_types', ['id'], unique=False)
    op.create_index(op.f('ix_body_types_name'), 'body_types', ['name'], unique=False)
    op.create_table('equipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['equipment_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipments_id'), 'equipments', ['id'], unique=False)
    op.create_index(op.f('ix_equipments_name'), 'equipments', ['name'], unique=False)
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_models_id'), 'models', ['id'], unique=False)
    op.create_index(op.f('ix_models_name'), 'models', ['name'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=False),
    sa.Column('engine_displacement', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('kilowatts', sa.Integer(), nullable=False),
    sa.Column('horsepowers', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('doors_number', sa.String(), nullable=True),
    sa.Column('payload_capacity', sa.String(), nullable=True),
    sa.Column('axle_count', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fuel_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('emission_standard_id', sa.Integer(), nullable=False),
    sa.Column('drivetrain_id', sa.Integer(), nullable=False),
    sa.Column('transmission_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_type_id', sa.Integer(), nullable=False),
    sa.Column('body_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['body_type_id'], ['body_types.id'], ),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['drivetrain_id'], ['drivetrains.id'], ),
    sa.ForeignKeyConstraint(['emission_standard_id'], ['emission_standards.id'], ),
    sa.ForeignKeyConstraint(['fuel_id'], ['fuels.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['transmission_id'], ['transmissions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_type_id'], ['vehicle_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_axle_count'), 'posts', ['axle_count'], unique=False)
    op.create_index(op.f('ix_posts_color'), 'posts', ['color'], unique=False)
    op.create_index(op.f('ix_posts_doors_number'), 'posts', ['doors_number'], unique=False)
    op.create_index(op.f('ix_posts_engine_displacement'), 'posts', ['engine_displacement'], unique=False)
    op.create_index(op.f('ix_posts_horsepowers'), 'posts', ['horsepowers'], unique=False)
    op.create_index(op.f('ix_posts_id'), 'posts', ['id'], unique=False)
    op.create_index(op.f('ix_posts_kilowatts'), 'posts', ['kilowatts'], unique=False)
    op.create_index(op.f('ix_posts_mileage'), 'posts', ['mileage'], unique=False)
    op.create_index(op.f('ix_posts_payload_capacity'), 'posts', ['payload_capacity'], unique=False)
    op.create_index(op.f('ix_posts_price'), 'posts', ['price'], unique=False)
    op.create_index(op.f('ix_posts_title'), 'posts', ['title'], unique=False)
    op.create_index(op.f('ix_posts_year'), 'posts', ['year'], unique=False)
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('is_primary', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_id'), 'images', ['id'], unique=False)
    op.create_table('post_equipments',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipments.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'equipment_id')
    )
    op.drop_column('users', 'has_viber')
    op.drop_column('users', 'has_whatsapp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('has_whatsapp', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('has_viber', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_table('post_equipments')
    op.drop_index(op.f('ix_images_id'), table_name='images')
    op.drop_table('images')
    op.drop_index(op.f('ix_posts_year'), table_name='posts')
    op.drop_index(op.f('ix_posts_title'), table_name='posts')
    op.drop_index(op.f('ix_posts_price'), table_name='posts')
    op.drop_index(op.f('ix_posts_payload_capacity'), table_name='posts')
    op.drop_index(op.f('ix_posts_mileage'), table_name='posts')
    op.drop_index(op.f('ix_posts_kilowatts'), table_name='posts')
    op.drop_index(op.f('ix_posts_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_horsepowers'), table_name='posts')
    op.drop_index(op.f('ix_posts_engine_displacement'), table_name='posts')
    op.drop_index(op.f('ix_posts_doors_number'), table_name='posts')
    op.drop_index(op.f('ix_posts_color'), table_name='posts')
    op.drop_index(op.f('ix_posts_axle_count'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_models_name'), table_name='models')
    op.drop_index(op.f('ix_models_id'), table_name='models')
    op.drop_table('models')
    op.drop_index(op.f('ix_equipments_name'), table_name='equipments')
    op.drop_index(op.f('ix_equipments_id'), table_name='equipments')
    op.drop_table('equipments')
    op.drop_index(op.f('ix_body_types_name'), table_name='body_types')
    op.drop_index(op.f('ix_body_types_id'), table_name='body_types')
    op.drop_table('body_types')
    op.drop_index(op.f('ix_vehicle_types_name'), table_name='vehicle_types')
    op.drop_index(op.f('ix_vehicle_types_id'), table_name='vehicle_types')
    op.drop_table('vehicle_types')
    op.drop_index(op.f('ix_transmissions_name'), table_name='transmissions')
    op.drop_index(op.f('ix_transmissions_id'), table_name='transmissions')
    op.drop_table('transmissions')
    op.drop_index(op.f('ix_locations_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_country'), table_name='locations')
    op.drop_index(op.f('ix_locations_city'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_fuels_name'), table_name='fuels')
    op.drop_index(op.f('ix_fuels_id'), table_name='fuels')
    op.drop_table('fuels')
    op.drop_index(op.f('ix_equipment_categories_name'), table_name='equipment_categories')
    op.drop_index(op.f('ix_equipment_categories_id'), table_name='equipment_categories')
    op.drop_table('equipment_categories')
    op.drop_index(op.f('ix_emission_standards_name'), table_name='emission_standards')
    op.drop_index(op.f('ix_emission_standards_id'), table_name='emission_standards')
    op.drop_table('emission_standards')
    op.drop_index(op.f('ix_drivetrains_name'), table_name='drivetrains')
    op.drop_index(op.f('ix_drivetrains_id'), table_name='drivetrains')
    op.drop_table('drivetrains')
    op.drop_index(op.f('ix_brands_name'), table_name='brands')
    op.drop_index(op.f('ix_brands_id'), table_name='brands')
    op.drop_table('brands')
    # ### end Alembic commands ###
